version: '3.8'

services:
  db:
    container_name: glimmershop_pg_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"

  pgadmin:
    container_name: glimmershop_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "8888:80"

  redis:
    container_name: glimmershop_redis_container
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
