version: '3.8'
services:
  db:
    container_name: glimmershop_pg_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
  pgadmin:
    container_name: glimmershop_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "8888:80"