"""Revert test changes

Revision ID: 15877271074c
Revises: 8b51162039cd
Create Date: 2024-12-29 16:39:28.243036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15877271074c'
down_revision = '8b51162039cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_cart_id'), 'cart', ['id'], unique=False, schema='public')
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['public.cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['public.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_cart_item_id'), 'cart_item', ['id'], unique=False, schema='public')
    op.drop_constraint('product_seller_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'user', ['seller_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('product_category_category_id_fkey', 'product_category', type_='foreignkey')
    op.drop_constraint('product_category_product_id_fkey', 'product_category', type_='foreignkey')
    op.create_foreign_key(None, 'product_category', 'category', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'product_category', 'product', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('user_order_product_id_fkey', 'user_order', type_='foreignkey')
    op.drop_constraint('user_order_user_id_fkey', 'user_order', type_='foreignkey')
    op.create_foreign_key(None, 'user_order', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'user_order', 'product', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_order', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_order', schema='public', type_='foreignkey')
    op.create_foreign_key('user_order_user_id_fkey', 'user_order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_order_product_id_fkey', 'user_order', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'product_category', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product_category', schema='public', type_='foreignkey')
    op.create_foreign_key('product_category_product_id_fkey', 'product_category', 'product', ['product_id'], ['id'])
    op.create_foreign_key('product_category_category_id_fkey', 'product_category', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'product', schema='public', type_='foreignkey')
    op.create_foreign_key('product_seller_id_fkey', 'product', 'user', ['seller_id'], ['id'])
    op.drop_index(op.f('ix_public_cart_item_id'), table_name='cart_item', schema='public')
    op.drop_table('cart_item', schema='public')
    op.drop_index(op.f('ix_public_cart_id'), table_name='cart', schema='public')
    op.drop_table('cart', schema='public')
    # ### end Alembic commands ###
